/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.43
 * Generated at: 2021-04-06 21:22:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class TaglibTest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("cs3220:leetTalk", cs3220.tag.Functions.class, "leetTalk", new Class[] {java.lang.String.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/cs3220.tld", Long.valueOf(1617743930532L));
    _jspx_dependants.put("/WEB-INF/tags/greeting.tag", Long.valueOf(1617743319539L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>TaglibTest</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<p>The sum of 10 and 20 is ");
      if (_jspx_meth_cs3220_005fadd_005f0(_jspx_page_context))
        return;
      out.write(".</p>\r\n");
      out.write("<p>The sum of ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.a}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" and ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.b}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" is ");
      if (_jspx_meth_cs3220_005fadd_005f1(_jspx_page_context))
        return;
      out.write(".</p>\r\n");
      out.write("\r\n");
      out.write("<p>Request Info</p>\r\n");
      out.write("<ul>\r\n");
      out.write("  <li>Method: ");
      if (_jspx_meth_cs3220_005frequestInfo_005f0(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("  <li>URI: ");
      if (_jspx_meth_cs3220_005frequestInfo_005f1(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("  <li>Client Address: ");
      if (_jspx_meth_cs3220_005frequestInfo_005f2(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("  <li>Server Address: ");
      if (_jspx_meth_cs3220_005frequestInfo_005f3(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("</ul>\r\n");
      out.write("\r\n");
      out.write("<p>");
      if (_jspx_meth_cs3220_005fcap_005f0(_jspx_page_context))
        return;
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("<p>");
      if (_jspx_meth_cs3220_005fgreeting_005f0(_jspx_page_context))
        return;
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("<p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cs3220:leetTalk(\"fear my mad programming skills\")}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_cs3220_005fadd_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cs3220:add
    cs3220.tag.AddTag _jspx_th_cs3220_005fadd_005f0 = new cs3220.tag.AddTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_cs3220_005fadd_005f0);
    try {
      _jspx_th_cs3220_005fadd_005f0.setJspContext(_jspx_page_context);
      // /TaglibTest.jsp(10,27) name = op1 type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cs3220_005fadd_005f0.setOp1(10);
      // /TaglibTest.jsp(10,27) name = op2 type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cs3220_005fadd_005f0.setOp2(20);
      _jspx_th_cs3220_005fadd_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_cs3220_005fadd_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_cs3220_005fadd_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cs3220:add
    cs3220.tag.AddTag _jspx_th_cs3220_005fadd_005f1 = new cs3220.tag.AddTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_cs3220_005fadd_005f1);
    try {
      _jspx_th_cs3220_005fadd_005f1.setJspContext(_jspx_page_context);
      // /TaglibTest.jsp(11,43) name = op1 type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cs3220_005fadd_005f1.setOp1(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.a}", int.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).intValue());
      // /TaglibTest.jsp(11,43) name = op2 type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cs3220_005fadd_005f1.setOp2(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.b}", int.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).intValue());
      _jspx_th_cs3220_005fadd_005f1.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_cs3220_005fadd_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_cs3220_005frequestInfo_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cs3220:requestInfo
    cs3220.tag.RequestInfoTag _jspx_th_cs3220_005frequestInfo_005f0 = new cs3220.tag.RequestInfoTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_cs3220_005frequestInfo_005f0);
    try {
      _jspx_th_cs3220_005frequestInfo_005f0.setJspContext(_jspx_page_context);
      // /TaglibTest.jsp(15,14) name = type type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cs3220_005frequestInfo_005f0.setType("method");
      _jspx_th_cs3220_005frequestInfo_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_cs3220_005frequestInfo_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_cs3220_005frequestInfo_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cs3220:requestInfo
    cs3220.tag.RequestInfoTag _jspx_th_cs3220_005frequestInfo_005f1 = new cs3220.tag.RequestInfoTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_cs3220_005frequestInfo_005f1);
    try {
      _jspx_th_cs3220_005frequestInfo_005f1.setJspContext(_jspx_page_context);
      // /TaglibTest.jsp(16,11) name = type type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cs3220_005frequestInfo_005f1.setType("uri");
      _jspx_th_cs3220_005frequestInfo_005f1.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_cs3220_005frequestInfo_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_cs3220_005frequestInfo_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cs3220:requestInfo
    cs3220.tag.RequestInfoTag _jspx_th_cs3220_005frequestInfo_005f2 = new cs3220.tag.RequestInfoTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_cs3220_005frequestInfo_005f2);
    try {
      _jspx_th_cs3220_005frequestInfo_005f2.setJspContext(_jspx_page_context);
      // /TaglibTest.jsp(17,22) name = type type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cs3220_005frequestInfo_005f2.setType("client");
      _jspx_th_cs3220_005frequestInfo_005f2.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_cs3220_005frequestInfo_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_cs3220_005frequestInfo_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cs3220:requestInfo
    cs3220.tag.RequestInfoTag _jspx_th_cs3220_005frequestInfo_005f3 = new cs3220.tag.RequestInfoTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_cs3220_005frequestInfo_005f3);
    try {
      _jspx_th_cs3220_005frequestInfo_005f3.setJspContext(_jspx_page_context);
      // /TaglibTest.jsp(18,22) name = type type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_cs3220_005frequestInfo_005f3.setType("server");
      _jspx_th_cs3220_005frequestInfo_005f3.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_cs3220_005frequestInfo_005f3);
    }
    return false;
  }

  private boolean _jspx_meth_cs3220_005fcap_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cs3220:cap
    cs3220.tag.CapTag _jspx_th_cs3220_005fcap_005f0 = new cs3220.tag.CapTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_cs3220_005fcap_005f0);
    try {
      _jspx_th_cs3220_005fcap_005f0.setJspContext(_jspx_page_context);
      _jspx_th_cs3220_005fcap_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_cs3220_005fcap_005f0, null));
      _jspx_th_cs3220_005fcap_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_cs3220_005fcap_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_cs3220_005fgreeting_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cs3220:greeting
    org.apache.jsp.tag.web.greeting_tag _jspx_th_cs3220_005fgreeting_005f0 = new org.apache.jsp.tag.web.greeting_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_cs3220_005fgreeting_005f0);
    try {
      _jspx_th_cs3220_005fgreeting_005f0.setJspContext(_jspx_page_context);
      // /TaglibTest.jsp(23,3) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_cs3220_005fgreeting_005f0.setName("cguo");
      _jspx_th_cs3220_005fgreeting_005f0.setJspBody(new Helper( 1, _jspx_page_context, _jspx_th_cs3220_005fgreeting_005f0, null));
      _jspx_th_cs3220_005fgreeting_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_cs3220_005fgreeting_005f0);
    }
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private javax.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, javax.servlet.jsp.JspContext jspContext, javax.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("Hello World");
      return false;
    }
    public boolean invoke1( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("Hello");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws javax.servlet.jsp.JspException
    {
      javax.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(javax.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
          case 1:
            invoke1( out );
            break;
        }
        jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof javax.servlet.jsp.SkipPageException)
            throw (javax.servlet.jsp.SkipPageException) e;
        throw new javax.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
