/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.43
 * Generated at: 2021-03-27 23:32:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class CurrencyGet_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("file:/C:/apache-tomcat-9.0.43/lib/standard.jar", Long.valueOf(1098740024000L));
    _jspx_dependants.put("jar:file:/C:/apache-tomcat-9.0.43/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098736290000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("  <link rel=\"stylesheet\" \r\n");
      out.write("    href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" \r\n");
      out.write("    integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" \r\n");
      out.write("    crossorigin=\"anonymous\">\r\n");
      out.write("  <link rel=\"stylesheet\" \r\n");
      out.write("    href=\"https://use.fontawesome.com/releases/v5.7.2/css/all.css\"\r\n");
      out.write("    integrity=\"sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr\"\r\n");
      out.write("    crossorigin=\"anonymous\">\r\n");
      out.write("<title>CurrencyGet</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"container\">\r\n");
      out.write("  <nav class=\"navbar navbar-expand-lg navbar-light\">\r\n");
      out.write("    <a class=\"navbar-brand mr-2\" href=\"#\">\r\n");
      out.write("      <div class=\"\">\r\n");
      out.write("        <i class=\"fab fa-bitcoin fa-lg\"></i>\r\n");
      out.write("        <a class=\"navlink mr-2 text-dark h5\" \r\n");
      out.write("          href=\"http://cs3.calstatela.edu/~cguo/cs3220/lab/mybargains.html#\">My Bargains </a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </a>\r\n");
      out.write("    <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" \r\n");
      out.write("    aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("      <ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("        <li class=\"nav-item active mr-2\">\r\n");
      out.write("          <a class=\"navlink text-muted\" href=\"http://cs3.calstatela.edu/~cguo/cs3220/lab/mybargains.html#\">Stores </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item active mr-2\">\r\n");
      out.write("          <a class=\"navlink text-muted\" href=\"http://cs3.calstatela.edu/~cguo/cs3220/lab/mybargains.html#\">Computers </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item active mr-2\">\r\n");
      out.write("          <a class=\"navlink text-muted\" href=\"http://cs3.calstatela.edu/~cguo/cs3220/lab/mybargains.html#\">Electronics </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item active\">\r\n");
      out.write("          <a class=\"navlink text-muted\" href=\"http://cs3.calstatela.edu/~cguo/cs3220/lab/mybargains.html#\">\r\n");
      out.write("            Life Style &amp; Home</a>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"row\">\r\n");
      out.write("    <div id=\"left\" class=\"col-lg-7\">\r\n");
      out.write("\r\n");
      out.write("      <div style=\"min-height: 200px;\" class=\"d-none d-lg-block p-3 mb-2 bg-warning text-dark\">AD 1</div>\r\n");
      out.write("\r\n");
      out.write("      <h3 class=\"border-bottom my-4 pb-2\">Latest Deals</h3>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"card mb-3\">\r\n");
      out.write("        <div class=\"card-header\">Posted by John 4 hours ago</div>\r\n");
      out.write("        <div class=\"card-body\">\r\n");
      out.write("          <h5 class=\"card-title\">Deal 1</h5>\r\n");
      out.write("          <p class=\"card-text\">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quam\r\n");
      out.write("          recusandae beatae itaque, odio praesentium modi quos dolores! Vero\r\n");
      out.write("          dicta, quisquam ullam velit non quam facere cupiditate. Facere saepe\r\n");
      out.write("          illo esse?</p>\r\n");
      out.write("          <a href=\"http://cs3.calstatela.edu/~cguo/cs3220/lab/mybargains.html#\" class=\"btn btn-info\">See Deal</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"card mb-3\">\r\n");
      out.write("        <div class=\"card-header\">Posted by John 5 hours ago</div>\r\n");
      out.write("        <div class=\"card-body\">\r\n");
      out.write("          <h5 class=\"card-title\">Deal 2</h5>\r\n");
      out.write("          <p class=\"card-text\">Odio voluptatum tenetur, ullam ratione minima ea error libero\r\n");
      out.write("          voluptatibus voluptate, et autem deleniti tempore illum vitae nisi\r\n");
      out.write("          eius magni cum? Cumque maiores excepturi saepe cupiditate, eaque sit\r\n");
      out.write("          veritatis nam.</p>\r\n");
      out.write("          <a href=\"http://cs3.calstatela.edu/~cguo/cs3220/lab/mybargains.html#\" class=\"btn btn-info\">See Deal</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"card mb-3\">\r\n");
      out.write("        <div class=\"card-header\">Posted by John 6 hours ago</div>\r\n");
      out.write("        <div class=\"card-body\">\r\n");
      out.write("          <h5 class=\"card-title\">Deal 3</h5>\r\n");
      out.write("          <p class=\"card-text\">Sit minus qui corporis perspiciatis fuga quo ipsam,\r\n");
      out.write("          est iste laudantium illo, neque atque quos excepturi harum, soluta\r\n");
      out.write("          sequi aliquid beatae cupiditate voluptatibus rerum iure! Tenetur\r\n");
      out.write("          neque vitae expedita nemo.</p>\r\n");
      out.write("          <a href=\"http://cs3.calstatela.edu/~cguo/cs3220/lab/mybargains.html#\" class=\"btn btn-info\">See Deal</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"right\" class=\"col-lg-5 d-none d-lg-block\">\r\n");
      out.write("      <div style=\"min-height: 200px;\" class=\"p-3 mb-2 bg-warning text-dark\">AD 2</div>\r\n");
      out.write("\r\n");
      out.write("      <h3 class=\"border-bottom my-4 pb-2\">Trending Deals</h3>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"card mb-3\">\r\n");
      out.write("        <div class=\"card-body\">\r\n");
      out.write("          <h5 class=\"card-title\">Deal 4</h5>\r\n");
      out.write("          <p class=\"card-text\">Odio voluptatum tenetur, ullam ratione minima ea\r\n");
      out.write("            error libero voluptatibus voluptate, et autem deleniti tempore illum\r\n");
      out.write("            vitae nisi eius magni cum? Cumque maiores excepturi saepe cupiditate,\r\n");
      out.write("            eaque sit veritatis nam.?</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"card mb-3\">\r\n");
      out.write("        <div class=\"card-body\">\r\n");
      out.write("          <h5 class=\"card-title\">Deal 5</h5>\r\n");
      out.write("          <p class=\"card-text\">Repellat dolorum animi fuga nisi consequuntur eligendi magni,\r\n");
      out.write("          laboriosam quo tenetur maiores necessitatibus nobis architecto debitis\r\n");
      out.write("          odio officiis beatae, nostrum fugiat. Ducimus odio consequatur eveniet\r\n");
      out.write("          ex magni adipisci praesentium alias.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"card\">\r\n");
      out.write("        <div class=\"card-body\">\r\n");
      out.write("          <h5 class=\"card-title\">Deal 6</h5>\r\n");
      out.write("          <p class=\"card-text\">Aspernatur delectus, quam ipsam rem libero odit voluptatibus maxime\r\n");
      out.write("          sunt quo neque modi nam odio minus consequatur. Beatae, dolor ex. Sequi\r\n");
      out.write("          dolore earum sit voluptates impedit veniam iusto odit ea</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <div class=\"p-3 mb-2 bg-light text-dark text-center\">\r\n");
      out.write("    Copyright © 2018-2020, Chengyu Sun. All rights reserved.\r\n");
      out.write("  </div>\r\n");
      out.write("\t\r\n");
      out.write("\t    <script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\" \r\n");
      out.write("    integrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\" \r\n");
      out.write("    integrity=\"sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\" \r\n");
      out.write("    integrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
